name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: Install dependencies
        run: npm ci
      - name: Install Obsidian
        run: |
          wget -q https://github.com/obsidianmd/obsidian-releases/releases/download/v0.12.19/Obsidian-0.12.19-universal.dmg
          sudo hdiutil attach Obsidian-0.12.19-universal.dmg
          sudo cp -rf "/Volumes/Obsidian 0.12.19-universal/Obsidian.app" /Applications
          sudo hdiutil detach "/Volumes/Obsidian 0.12.19-universal"
      - name: Lint
        run: npm run lint
      - name: Test
        run: |
          npm run build-with-tests
          npm test
      - name: Build
        run: npm run build
      - name: Upload main.js
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: main.js
          asset_name: main.js
          asset_content_type: text/javascript
      - name: Upload manifest.json
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: manifest.json
          asset_name: manifest.json
          asset_content_type: application/json
      - name: Upload styles.css
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: styles.css
          asset_name: styles.css
          asset_content_type: text/css
